POST http://localhost:8081/api/v1/auth/signup
Content-Type: application/json

{
  "email": "ivan2001.forever@gmail.com",
  "username": "abobus",
  "password": "bebra4"
}
###
GET http://localhost:8081/api/v1/activation?link=b07590e8-709a-46b6-9bd1-be6b0e9bf6ac
###
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "username": "abobus",
  "password": "bebra4"
}

###
POST http://localhost:8081/api/v1/auth/logout
Content-Type: application/json

{}

###
