POST http://localhost:8081/api/v1/auth/signup
Content-Type: application/json

{
  "email": "vsratushkin@gmail.com",
  "username": "owner",
  "password": "owner"
}
###
GET http://localhost:8081/api/v1/activation?link=09b3323d-3b5d-4aa5-9fc6-c7f5e51ccd7f
###
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "username": "owner",
  "password": "owner"
}

###
POST http://localhost:8081/api/v1/auth/logout
Content-Type: application/json

{}

###
