POST http://localhost:8081/api/v1/clothes
Content-Type: application/json

{
  "name": "aboba",
  "collectionId": "edb1f964-668a-4327-87d2-8946526f93a5",
  "price": 1399.3,
  "photos": ["1","2","3"]
}

###
GET http://localhost:8081/api/v1/clothes/c0e27f33-1edc-408a-8da4-b2db4c2e1ac


###
